exclude_patterns:
- "test/"
- "spec/"
- "**/vendor/"
- "node_modules"
- ".git/"
- ".github/"
- ".nyc_output/"
- "coverage/"
- "platforms/"
- "plugins/"
- "www/css/"
- "www/dist/"
- "webpack.dev.config.js"
- "webpack.prod.config.js"
