version: "3"
networks:
    project13net:
services:
    server:
        image: dundgren/bikerental-api:1.5
        container_name: "bikerental-api"
        ports:
            - 1337:1337
        networks:
            project13net:
        restart:
            "always"
    oauth:
        image: jeso20/bikerental-oauth:1.1
        container_name: "bikerental-oauth"
        ports:
            - 666:666
        networks:
            project13net:
    app:
        image: jeso20/bikerental-client-app:1.3
        container_name: "bikerental-client-app"
        ports:
            - 8000:8000
        networks:
            project13net:
    webbclient:
        image: jeso20/bikerental-client-webbclient:1.2
        container_name: "bikerental-client-webbclient"
        ports:
            - 8020:8020
        networks:
            project13net:
