version: "3"
networks:
    project13net:
services:
    server:
        image: dundgren/bikerental-api:1.4
        container_name: "bikerental-api"
        ports:
            - 1337:1337
        networks:
            project13net:
        restart:
            "always"
    oauth:
        image: jeso20/bikerental-oauth:1.1
        container_name: "bikerental-oauth"
        ports:
            - 666:666
        networks:
            project13net:
