name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
    CLIENTID: ${{ secrets.CLIENTID}}
    DBTOKEN: ${{ secrets.DBSECRET}}
    LOCALHOST: ${{ secrets.LOCALHOST}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - name: Run tests
        run: npm test
